openapi: 3.0.3
info:
  title: Digital Assets Recommendation Engine
  description: ping pong
  termsOfService: https://no.terms.yet
  contact:
    email: ankur.vatsa@gmail.com
  license:
    name: GNU GPLv3
    url: https://github.com/vatsaaa/dare/LICENSE.md
  version: 1.0.0
externalDocs:
  description: README.md
  url: http://fix.please
servers:
  - url: /api/v1
paths:
  /ping:
    get:
      summary: Health check url
      operationId: controllers.controllers.ping
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
            default: vatsaaa
          description: Ping to pong
      tags:
        - Health check
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid status value

      
